### ISSUE TITLE
Needs checklist for setting up a workshop

### ISSUE THREAD

**Issue by mr-c** [NLeSC/cwl-tutorial#1]
- [ ] test instructions and record the known working version
- [ ] Send out explicit preparation instructions
  - Python 2.7
  - Linux, OS X, MS Windows Bash
- [ ] room checklist:
   - number of seats
   - tables
   - power outlets
- [ ] Sticky notes, two colors
- [ ] hold space for those who signed up
- [ ] print outs or second monitor with fully written CWL descriptions for reference
- [ ] remove content based on time available

**Comment by mr-c** [comment]
Many notes from @hmenager -- special thanks to him for helping me out at the CWL workshop delivered at the ELIXIR 2017 All Hands Meeting and for the feedback.
